### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ashishbijlani** [rs3lab/KFlex#1]
Hello,

NOTE: this is a question, not an issue.

In the paper, I saw you compared Redis vs eBPF-KFlex+Redis cache performance. Did you get a chance to evaluate eBPF+Redis cache performance without KFlex extensions?

Thanks,
Ashish

**Comment by kkdwvd** [comment]
We did not, but mostly because it was difficult / infeasible.

We implemented two PoCs.
* SETS/GETS, reusing most of the memcache infrastructure and swapping out the payload parsing to support Redis (and serialize all updates to the underlying hash table), which eBPF won't allow you to do (as map helpers cannot be called while holding BPF spin locks, due to the possibility of deadlocks).
* ZADD, which wasn't feasible to do in eBPF because it requires maintaining a hash table of skip lists ordered by score, the latter being a data structure that is unsupported, and required multiple levels of allocations.

In reality, for a full blown offload, performance will be dictated by other factors as well (key-value size, pipelining which we didn't support, etc.) so wins may be smaller, especially when not running at the XDP hook. That said, the main focus was to demonstrate that KFlex allows users to implement such functionality inside kernel extensions.

**Comment by ashishbijlani** [comment]
Thanks for your prompt response!

>  the main focus was to demonstrate that KFlex allows users to implement such functionality inside kernel extensions.

If the main focus was to simply show what's possible, then it makes sense. However, the paper highlights performance gains from KFlex eBPF cache for Redis, but does not provide delta over non-KFlex eBPF cache. 

As a reader, I'm clueless on what the source of performance improvement for Redis is: is it the KFlex framework or simply because eBPF cache can now bypass TCP/IP stack? Do you think it is feasible to implement a simple eBPF cache for just GET operations and single thread Redis (i.e., no spin locks) in order to understand the performance delta?

**Comment by kkdwvd** [comment]
> If the main focus was to simply show what's possible, then it makes sense. However, the paper highlights performance gains from KFlex eBPF cache for Redis, but does not provide delta over non-KFlex eBPF cache.

But that’s because it is _not_ possible to do the same with eBPF as is, so I’m not sure how we compare a case that is impossible to construct.

> As a reader, I'm clueless on what the source of performance improvement for Redis is: is it the KFlex framework or simply because eBPF cache can now bypass TCP/IP stack?

The performance improvement is because you can offload logic into the kernel, KFlex is just a means that allows you to do that.

> Do you think it is feasible to implement a simple eBPF cache for just GET operations and single thread Redis (i.e., no spin locks) in order to understand the performance delta?

No, in fact this would be an unfair comparison. The network stack in case of user space Redis probably still processes packets for it across different cores with RSS even if user space Redis is single threaded, to avoid holding a spin lock you’d have to force network processing to a single core. The reason you need to hold it to simulate single threaded application behavior is because the eBPF program is invoked to do application layer processing on multiple cores in parallel.

We compare where a reasonable eBPF baseline exists, e.g. BMC’s read-mostly case. If you go for 100% reads, you will have little to no difference between KFlex and BMC. The performance _improvement_ is not really derived from KFlex in the end, it just expands the set of use cases that can benefit from running code inside the kernel.

**Comment by kkdwvd** [comment]
> Do you think it is feasible to implement a simple eBPF cache for just GET operations and single thread Redis (i.e., no spin locks) in order to understand the performance delta?

To answer this in short, say you did manage to create such a case where holding the lock is unnecessary (you prefill the hash table and it’s read only), you’d have little to no difference between an eBPF offload and a KFlex offload, the performance should be equivalent. So in the end, the performance improvement for applications is from being able to implement more use cases that were previously difficult or infeasible inside eBPF programs using KFlex.
